# Generated by Django 6.1 on 2026-08-26 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Order number must be in the format ORD-XXXXXXXX (8 hex digits, uppercase).', regex='^ORD-[0-9A-F]{8}$')]),
        ),
    ]
