# Generated by Django 6.1 on 2026-09-07 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Order number must be in the format ORD-XXXXXXXX.', regex='^ORD-[0-9A-F]{8}$')]),
        ),
    ]
