# Generated by Django 6.1 on 2026-08-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('event', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('family', 'Family'), ('business', 'Business'), ('maternity', 'Maternity'), ('newborn', 'Newborn')], max_length=20)),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'albums',
                'ordering': ['-created_at'],
            },
        ),
    ]
