# Generated by Django 6.1 on 2026-09-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='event',
            field=models.CharField(choices=[('weddings', 'Weddings'), ('birthday', 'Birthday'), ('family', 'Family'), ('business', 'Business'), ('maternity', 'Maternity'), ('newborn', 'Newborn')], max_length=20),
        ),
    ]
